### ISSUE TITLE
Update Slack Channel link in README

### ISSUE THREAD

**Issue by greghaynes** [awslabs/kro#134]
### Documentation Issue

**Location**: https://github.com/awslabs/kro/blob/main/README.md

**Current State**: The Slack channel link in the README points to https://kubernetes.slack.com/archives/XXX-TBD

**Suggested Changes**: Change this from a TBD channel to an actual slack channel.

**Additional Context**:

**Comment by a-hilaly** [comment]
We have https://github.com/kubernetes/community/pull/8143 pending :) - will update the doc as soon as it's live!

**Comment by a-hilaly** [comment]
@greghaynes it's live https://kubernetes.slack.com/archives/C081TMY9D6Y 🎉 - we'll update the links in the website soon!
