### ISSUE TITLE
Minor information regarding Slack

### ISSUE THREAD

**Issue by seifrajhi** [awslabs/kro#140]
### Documentation Issue

Hello,

All links in the GitHub and documentation website should lead to slack channel, but I cannot find in k8s workspace, is it same as #eks one ?

**Comment by a-hilaly** [comment]
Hi @seifrajhi, thank you for calling out this! We currently have a [PR requesting](https://github.com/kubernetes/community/pull/8143) `kro` channel in k8s slack. We will update the links as soon as it's merged! :)

**Comment by a-hilaly** [comment]
@seifrajhi it's live https://kubernetes.slack.com/archives/C081TMY9D6Y 🎉 - we'll update the links in the website soon!

**Comment by candonov** [comment]
The Readme link is updated: https://github.com/awslabs/kro/pull/154
