### ISSUE TITLE
[INSTALLATION FAILED] Unexpected status from HEAD request to Public ECR 403 Forbidden

### ISSUE THREAD

**Issue by namejsjeongkr** [awslabs/kro#153]
### Description

**Observed Behavior**: 
I'm trying to install kro in my EKS cluster. But unfortunately, It didn't work well. Is there any issue to pull kro image ?

**Expected Behavior**:

**Reproduction Steps** (Please include `ResourceGroup` and `Instances` files):

**Versions**:
- kro version: v0.1.0
- Kubernetes Version (`kubectl version`): v1.28.5

**Involved Controllers**:
- Controller URLs and Versions (if applicable):

**Error Logs** (if applicable)**:
```
Error: INSTALLATION FAILED: unexpected status from HEAD request to https://public.ecr.aws/v2/kro/kro/manifests/0.1.0: 403 Forbidden
```

* Please vote on this issue by adding a 👍 [reaction](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/) to the original issue to help the community and maintainers prioritize this request
* Please do not leave "+1" or "me too" comments, they generate extra noise for issue followers and do not help prioritize the request
* If you are interested in working on this issue or have submitted a pull request, please leave a comment

### Which option describes the most your issue?

Others (please specify)

**Comment by jlbutler** [comment]
This is likely due to stale credentials in your toolchain. ECR Public does not require credentials for pull, but if you do retrieve a token (e.g. `aws ecr-public get-login-password`), they expire after 12 hrs. 

Can you invoke `helm registry logout public.ecr.aws` and then try again?

**Comment by giedri** [comment]
In my case I had to delete ECR login items in Keychain Access app to get it working
